/* 
Comandos iniciales, Solo hacer la primera vez al crear

En cmd/terminal/bash:
Para crear la base de datos world:
----------3.1.1----------
createdb -U postgres world

Para agregar el script world.sql a la db:
----------3.1.2----------
psql -f "rutaArchivo" -U postgres -d world

*postgres como usuario default/super del postgresql
*/

----------3.1.3----------
--SELECT * FROM CITY;
SELECT * FROM COUNTRY;
--SELECT * FROM COUNTRYLANGUAGE

----------Simples3.2.1----------
SELECT POPULATION
FROM COUNTRY 
WHERE NAME = 'Argentina';

----------Simples3.2.3----------
SELECT NAME
FROM COUNTRY
WHERE CONTINENT = 'South America' 
	AND POPULATION > 15000000;
	
----------Simples3.2.7----------
SELECT 
	CONTINENT, 
	COUNT(NAME) AS CANTIDAD_DE_PAISES 
FROM COUNTRY
WHERE POPULATION > 20000000
GROUP BY CONTINENT
HAVING COUNT(NAME) > 15;

----------Subqueries3.2.2----------
SELECT NAME, LIFEEXPECTANCY
FROM COUNTRY
WHERE LIFEEXPECTANCY = (SELECT MIN(LIFEEXPECTANCY) FROM COUNTRY) 
OR LIFEEXPECTANCY = (SELECT MAX(LIFEEXPECTANCY) FROM COUNTRY);

----------Subqueries3.2.4----------
SELECT 
	CONTINENT 
FROM 
	(SELECT 
	 	CONTINENT, SUM(GNP) AS TOTAL_GNP 
	 FROM 
	 	COUNTRY 
	 GROUP BY 
	 	CONTINENT 
	 HAVING 
	 	SUM(GNP) > (SELECT SUM(GNP)/7 FROM COUNTRY) 
	 ORDER BY 
	 	TOTAL_GNP DESC)
AS CONTINENTES_POR_GNP;

----------Joins3.2.3----------
SELECT 
	LANGUAGE
FROM
	COUNTRY
LEFT JOIN 
	COUNTRYLANGUAGE
ON 
	CODE = COUNTRYCODE
WHERE 
	CONTINENT = (SELECT 
				 	CONTINENT 
				 FROM 
				 	(SELECT 
					 	CONTINENT, SUM(GNP) AS TOTAL_GNP 
					 FROM 
					 	COUNTRY 
					 WHERE 
					 	CONTINENT <> 'Antarctica' 
					 GROUP BY 
					 	CONTINENT 
					 ORDER BY 
					 	TOTAL_GNP ASC 
					 LIMIT 1) 
				 AS GNP_CONTINENTE_MAS_POBRE);

----------Joins3.2.4----------
---1---
SELECT NAME, POPULATION
FROM COUNTRY
ORDER BY NAME;

---2---
SELECT
	COUNTRY.NAME, 
	SUM(CITY.POPULATION) AS TOTAL_EN_CIUDADES, 
	TRUNC((SUM(CITY.POPULATION)/COUNTRY.POPULATION::DECIMAL)*100, 2) AS PORCENTAJE_EN_CIUDADES
FROM
	COUNTRY
LEFT JOIN 
	CITY
ON 
	CODE = COUNTRYCODE
GROUP BY
	COUNTRY.NAME, COUNTRY.POPULATION
ORDER BY
	PORCENTAJE_EN_CIUDADES DESC;
	
----------3.3----------
CREATE TABLE IF NOT EXISTS STATS (
	COUNTRYCODE CHAR(3) PRIMARY KEY,
	CANT_LENGUAS TEXT,
	POP_URBANA BIGINT,
	FOREIGN KEY (COUNTRYCODE)
		REFERENCES COUNTRY (CODE)
);

DROP TABLE IF EXISTS STATS;

INSERT INTO 
	STATS (COUNTRYCODE, CANT_LENGUAS, POP_URBANA)
	SELECT
		COUNTRY.CODE, COUNT(COUNTRYLANGUAGE.LANGUAGE), SUM(CITY.POPULATION)
	FROM
		COUNTRY
	INNER JOIN 
		COUNTRYLANGUAGE 
	ON 
		COUNTRYLANGUAGE.COUNTRYCODE = COUNTRY.CODE 
	INNER JOIN
		CITY
	ON
		CITY.COUNTRYCODE = COUNTRYLANGUAGE.COUNTRYCODE
	GROUP BY
		COUNTRY.CODE;

SELECT * FROM STATS;
SELECT * FROM COUNTRYLANGUAGE;

SELECT COUNT(LANGUAGE)
FROM COUNTRYLANGUAGE
WHERE COUNTRYCODE = 'BRA';

SELECT SUM(POPULATION)
FROM CITY
WHERE COUNTRYCODE = 'CHN';

SELECT 
	COUNTRY.CODE, COUNT(COUNTRYLANGUAGE.LANGUAGE)
	FROM
		COUNTRY
	LEFT JOIN 
		COUNTRYLANGUAGE 
	ON 
		COUNTRY.CODE = COUNTRYLANGUAGE.COUNTRYCODE 
	GROUP BY
		COUNTRY.CODE;
		

	
